spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/h2primary
    username:
    password:
  datasource-secondary:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/h2secondary
    username:
    password:
